// Login types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_USER = "LOAD_USER";
export const FAILED_AUTHENTICATION = "FAILED_AUTHENTICATION";
export const FAILED_LOAD_USER = "FAILED_LOAD_USER";
export const LOGOUT = "LOGOUT";

// Fastings
export const FETCH_FASTINGS = "FETCH_FASTINGS";
export const START_FASTING = "START_FASTING";
export const STOPPED_FASTING = "STOPPED_FASTING";
export const FAILED_FETCHING_FASTINGS = "FAILED_FETCHING_FASTINGS";
export const FAILED_START_FASTING = "FAILED_START_FASTING";
export const FAILED_STOPPED_FASTING = "FAILED_STOPPED_FASTING";

// common
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const START_LOADING = "START_LOADING";